
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;
worker_cpu_affinity auto;
events {
	worker_connections 768;
	multi_accept on;
	use epoll;

}

http {
        geo $conn_limit_map {
            default '';
        }
	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	server_tokens on;
	client_max_body_size 256M;
	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;
	map_hash_bucket_size 256;
	map_hash_max_size 8192;

        open_file_cache          max=5000 inactive=3600s;
        open_file_cache_valid    30s;
        open_file_cache_min_uses 2;
        open_file_cache_errors   on;

        # Enable QUIC and HTTP/3
        ssl_early_data on;
        http3_max_concurrent_streams 256;
        quic_gso on;
        http3 on;
        add_header Alt-Svc 'h3=":$server_port"; ma=86400';
        sendfile_max_chunk 16384;
        http2_max_concurrent_streams 256;


	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	#gzip on;

	 #gzip_vary on;
	 #gzip_proxied any;
	 #gzip_comp_level 6;
	 #gzip_buffers 16 8k;
	 #gzip_http_version 1.1;
	 #gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/ssr-bot.conf;
	include /etc/nginx/sites-enabled/*.conf;
	server_names_hash_bucket_size 128;
	include /etc/nginx/bad-bots.conf;
	#include /etc/nginx/ssr-bot.conf;
}
