map $http_user_agent $is_bot {
    default 0;
    ~*(googlebot|bingbot|slurp|duckduckbot|baiduspider|yandexbot|facebookexternalhit|twitterbot|linkedinbot|crawler|crawl|bot) 1;
}

###########jebelz.com/ae_en/*.html or jebelz.com/ae_ar/*.html############
map $request_uri $is_html {
    default 0;
    ~^/(ae_en|ae_ar)/.*\.html$ 1;
}

map "$is_bot:$is_html" $use_ssr {
    default 0;
    "1:1" 1;
}

######## *.jebelz.com/*/*.html#########
map $request_uri $sa_html {
    default 0;
    ~^/(sa_en|sa_ar|in|en|ar)/.*\.html$ 1;
}

map "$is_bot:$sa_html" $sa_use_ssr {
    default 0;
    "1:1" 1;
}

######################################
