#==============this conf is for ssr app===============#
    #location = /_next/test.txt {
    #return 200 "OK";
#}

    #location = /debug-ssr {
    #default_type text/plain;

    #return 200 "UA=$http_user_agent
    #BOT=$is_bot
    #URI=$request_uri
    #HTML=$sa_html
    #SSR=$sa_use_ssr
    #";
    #}
    # ===== DEBUG HEADERS =====
    #add_header X-Is-Bot $is_bot always;
    #add_header X-Is-Html $sa_html always;
    #add_header X-Use-Ssr $sa_use_ssr always;
    # =========================

	 error_page 418 = @ssr;

    if ($sa_use_ssr = 1) {
        return 418;
    }

    location @ssr {
	proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host ssr.jebelz.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
    }
   location ^~ /_next/ {
    proxy_pass http://127.0.0.1:3000;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}    


#====================End of SSR app conf===================#
